version: "3.8"

services:
  app:
    image: spira-training:latest
    build:
      context: .
    volumes:
      - .:/app
      - /app/.venv
    
  feature-engineering:
    image: spira-training:latest
    build:
      context: .
    environment:
      - PYTHONPATH=/app
    command: "poetry run python src/spira_training/apps/feature_engineering/feature_engineering.py"
    volumes:
      - .:/app
      - /app/.venv

  unit-tests:
    image: spira-training:latest
    build:
      context: .
    command: "poetry run pytest tests/unit"
    volumes:
      - .:/app
      - /app/.venv
      
  integration-tests:
    image: spira-training:latest
    build:
      context: .
    command: "poetry run pytest tests/integration"
    volumes:
      - .:/app
      - /app/.venv
      
